version: '3.2'

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
  mysql-data:
  home-dir:

services:
  app: &app-service
    #image: registry.gitlab.com/tarampampam/laravel-in-docker-with-rr/app:${CURRENT_IMAGES_TAG:-master}
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    restart: on-failure
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - ./docker/app/app-entrypoint.sh:/app-entrypoint.sh:ro
      - .:/app:cached
      - home-dir:/home/user:cached
    env_file:
      - ./docker/docker-compose.env
    ports:
      - '4001:80'
      - '4002:443'
    command: 'rr serve -v -d -c /app/.rr-new.yaml'
    #command: 'rr serve -v -d -c /app/.rr.local.yml'
    #command: 'rr serve -v -d -c /app/.rr.local-norefresh.yml'
    depends_on:
      - redis
      - mysql
    networks:
      - app-network

  queue:
    <<: *app-service
    user: "${CURRENT_USER:-0:0}"
    environment:
      STARTUP_DELAY: 5
    command: 'php /app/artisan queue:work --memory=64'
    ports: []

  redis:
    image: redis:${REDIS_VERSION:-5.0.6}-alpine
    volumes:
      - redis-data:/data:cached
    ports:
      - 6379
      - '4004:6379' # Port 4004 for connecting from localhost
    networks:
      - app-network

  redis-commander: # <https://github.com/joeferner/redis-commander>
    image: rediscommander/redis-commander:latest
    environment:
      REDIS_HOSTS: 'default:redis:6379:0,cache:redis:6379:1,sessions:redis:6379:2'
    ports:
      - '4003:8081'
    depends_on:
      - redis
    networks:
      - app-network

#  postgres:
#    image: postgres:${POSTGRES_VERSION:-11.4}-alpine
#    restart: always
#    environment:
#      POSTGRES_DB: 'forge'
#      POSTGRES_USER: 'forge'
#      POSTGRES_PASSWORD: 'forge'
#    volumes:
#      - pg-data:/var/lib/postgresql/data:rw
#    ports:
#      - 5432
#      - '4005:5432' # Port 4005 for connecting from localhost
#    networks:
#      - app-network

  mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: &mysql-root-password NaHodMir
            MYSQL_DATABASE: app
            MYSQL_USER: user
            MYSQL_PASSWORD: secret
        volumes:
            - mysql-data:/var/lib/mysql:rw
        ports: [3306, '4005:3306'] # Port 13306 for connecting from localhost using, for example, data-grip
        networks:
            - app-network

  phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        links:
            - mysql:db
        ports:
            - 4006:80
        depends_on:
            - mysql
        networks:
            - app-network
